name: neural_annealing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - libstdcxx-ng  # For box2d env
  - tensorboardx
  - pip:
    - jax  # CPU-only. Use "jax[cuda12]" for GPU.
    - torch
    - torchvision
    - black
    - swig
    - gymnasium[box2d]
    - tensorboard
