name: neural_annealing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - libstdcxx-ng  # For box2d env
  - tensorboardx
  - pip:
    - --upgrade pip
    - --upgrade "jax[cuda12]"
    - torch
    - torchvision
    - black
    - swig
    - gymnasium[box2d]